version: "3.3"

services:
  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    restart: always
    volumes:
       - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: apffhs123
      MYSQL_DATABASE: nodearct_gram

  app:
    image: mini-nodeact-gram
    tty: true
    depends_on:
      - db
    ports:
      - 3000:3000
      - 4000:4000
    volumes:
         - ./app:/app
    #restart: always


    
